UI/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;
using DAL.Models;
using BLL.Services.ReservationServices;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using BLL.Services;
using BLL.Services.PatientServices;
using Microsoft.AspNetCore.SignalR;
using UI.Hubs;
using Microsoft.AspNetCore.Authorization;

namespace UI.Controllers
{
    //[Authorize(Roles = "Receptionist")]
    public class BookingController : Controller
    {
        private readonly IDoctorService Doctor;

        private readonly IReservationServices Reserve;
        private readonly IPatientServices Patient;
        private readonly IHubContext<RealtimeHub> hub;

        public BookingController(IReservationServices Reserve , IDoctorService Doctor, IPatientServices Patient,IHubContext<RealtimeHub> hub)
        {
            this.Reserve = Reserve;
            this.Doctor = Doctor;
            this.Patient = Patient;
            this.hub = hub;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            ViewBag.PatientIdError = 1;
            return View();
        }
        [HttpPost]
        public JsonResult GetPatintData(string SSN)
        {
            //int id = (int)TempData["model"];
            //TempData["model"] = Patient.GetBySSN(SSN);
            var data = Patient.GetBySSN(SSN);
            return Json(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DailyDetectionViewModel Detect)
        {
            if (ModelState.IsValid)
            {
                if (Detect.PatientId != null)
                {
                    var Data = Reserve.Add(Detect);
                    await hub.Clients.User(Data).SendAsync("newDoctor");
                    if (Data != null)
                    {
                        ViewBag.Success = 1;

                    }
                    //  DailyDetectionViewModel obj = new DailyDetectionViewModel();

                    return View();
                }

                else
                {
                    ViewBag.PatientIdError = 0;
                    return View(Detect);

                }
            }
            return View(Detect);

        }

        //------------------ajax----------------------------------------------
        [HttpPost]
        public JsonResult GetDoctorByDepartmentID(int DeptId , int ShiftId)
        {
            var doctorData = Doctor.GetAll(DeptId , ShiftId);
            return Json(doctorData);
        }
    }
}

UI/Views/Booking/Create.cshtml
@model DAL.Models.DailyDetectionViewModel
@{
    Layout = "/Views/Shared/Layout/_ReseptionistLayout.cshtml";
    ViewBag.Title = "Make an Appointment";
}

@inject BLL.Services.DepartmentServices.IDepartmentSevice Dep
@inject BLL.Services.shiftServeses.IShiftServeses shift
@inject BLL.Services.PatientServices.IPatientServices patient


@section PageHeader{
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Make an appointment</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Make an Appointment</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
}



<form id="A1" class="mt-5 mb-2 p-2 rounded" asp-action="Create" asp-controller="Booking">
    <div class="d-flex align-items-end justify-content-start">
        <h5 class=" mt-3 ms-3 me-3">Patient Info</h5>
        <hr class="w-75">
    </div>

    <div class="row clearfix">
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <input type="hidden" id="btnId" asp-for="PatientId" />
            <div class="form-floating input-group">
                <span class="input-group-text" for="Name"><i class="fas fa-user" for="Name"></i></span>
                <input class="form-control form-control show-tick" type="search" list="UserName" id="exampleDataList"
                       placeholder="User name" asp-for="PatientId" />
                <datalist id="UserName">
                    <option value="">- Patient SSN -</option>
                    @foreach (var item in patient.GetAll())
                    {
                        <option value="@item.SSN" />
                        @item.Name
                    }
                </datalist>
                <label for="UserName">- Patient SSN -</label>
            </div>
            <span class="text-danger" asp-validation-for="PatientId"></span>


            @if (ViewBag.PatientIdError == 0)
            {
                <span class="text-danger">This Field is Required</span>
            }
        </div>

    </div>

    <div class="row clearfix">
        <!--User ID  -->
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-address-card"></i></span>
                <input type="text" class="form-control input" placeholder="User ID" readonly id="patientId" />
                <label for="number">Patient Name </label>
            </div>
        </div>
        <!-- date -->
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-calendar-alt"></i></span>
                <input type="text" class="form-control input" placeholder="date" readonly id="patientDate" />
                <label for="date"> BirthDate </label>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <!--address  -->
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-map-marked-alt"></i></span>
                <input type="text" class="form-control input" placeholder="address" readonly id="patientAddress" />
                <label for="text">Address </label>
            </div>
        </div>
        <!-- Phone -->
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-phone-alt"></i></span>
                <input type="number" class="form-control input" placeholder="Phone" maxlength="11" readonly
                       id="patientPhone" />
                <label for="Phone">Phone</label>
            </div>
        </div>
    </div>
    <!-- bookin info -->
    <div class="d-flex align-items-end justify-content-start">
        <h5 class=" mt-3 ms-3 me-3">Booking Info</h5>
        <hr class="w-75">
    </div>
    <div class="row clearfix">
        <!--shift  -->
        <div class="col-sm-6 mb-3">
            <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group mt-3">
                <span class="input-group-text" id="basic-addon1"><i class="far fa-clock"></i></span>
                <select asp-for="ShiftId" class="deeee form-select form-control form-control show-tick input" placeholder="shift"
                        id="slctShift">
                    <option value="-1">- Shift -</option>
                    @foreach (var item in shift.GetAll())
                    {
                        <option value="@item.Id">@item.StartShift.TimeOfDay - @item.EndShift.TimeOfDay</option>
                    }
                </select>
                <label for="shift">- Shift -</label>
            </div>
            <span class="text-danger" asp-validation-for="ShiftId"></span>
        </div>
        <!--department  -->
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group">
                <span class="input-group-text" for="Name"><i class="fas fa-clinic-medical"></i></span>
                <select class="deeee form-select form-control form-control show-tick input" placeholder="Department"
                        id="slctDepartment" asp-for="DepartmentId">
                    <option value="-1">- Departments -</option>
                    @foreach (var item in Dep.GetAllDepartmentForBooking())
                    {

                        <option value="@item.DepartmentId">@item.Name</option>
                    }
                </select>
                <label for="floatingInput">- Departments -</label>
            </div>
            <span class="text-danger" asp-validation-for="DepartmentId"></span>
        </div>
    </div>
    <div class="row clearfix">
        <!-- doctor -->
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group">
                <span class="input-group-text" for="Name"><i class="fas fa-user-md"></i></span>
                <select class="form-select form-control form-control show-tick input" placeholder="shift"
                        id="slctDoctor" asp-for="DoctorId">
                    <option value="">- doctor -</option>
                </select>
                <label for="floatingInput">- Doctor -</label>
            </div>
            <span class="text-danger" asp-validation-for="DoctorId"></span>
        </div>

        <!--time  -->
        <div class="col-sm-6 mb-3 mt-3">
            <div class="alert alert-warning alert-dismissible fade show mb-1 d-none" role="alert">
                You should check in on some of those fields below.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="form-floating input-group">
                <span class="input-group-text" for="Name"><i class="fas fa-clock"></i></span>
                <input id="time" type="datetime-local" data-provide="datepicker" data-date-autoclose="true"
                       class="form-control input" placeholder="time" required asp-for="DateAndTime" />
                <label for="time">Time</label>
            </div>
            <span class="text-danger" asp-validation-for="DateAndTime"></span>
        </div>
    </div>
    <div class="row clearfix">
    </div>

    <div class="mt-3">
        <div class="form-group mb-4 pt-2">
            <button type="submit" class="btn btn-save ">Booking</button>
            <button type="reset" class="btn btn-outline-secondary">Reset</button>
        </div>
        <div class="form-group mb-4 pt-2">
            <button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>
        </div>
    </div>
</form>




<script src="~/jquery/jquery.min.js"></script>
<!-- Validation Plugin Js -->
<script src="~/jquery-validate/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("#exampleDataList").change(function () {
        var patientId = $("#exampleDataList").val();
        
        $.ajax({

            type: "POST",
            url: "/Booking/GetPatintData",
            data: { SSN: patientId },

            success: function (res) {
                $("#patientId").val(res.name);
                $("#patientAddress").val(res.address);
                $("#patientPhone").val(res.phone);
                $("#patientDate").val(res.birthDate);
                $("#btnId").val(res.id);
            }

        });
    })

    $(".deeee").change(function () {

        $("#slctDoctor").empty();
        $("#slctDoctor").append("<option>Choose Doctor</option>");

        var DeptId = $("#slctDepartment").val();

        var ShiftId = $("#slctShift").val();
        if (DeptId != 0 && ShiftId != 0) {

            $.ajax({

                type: "POST",
                url: "/Booking/GetDoctorByDepartmentID",
                data: {
                    DeptId: DeptId,
                    ShiftId: ShiftId
                },

                success: function (res) {

                    $.each(res, function (i, e) {
                        $("#slctDoctor").append("<option value='" + e.id + "'>" + e.name + "</option>");
                    });
                }

            });
        }


    });

    $(document).ready(function () {
        var DeptId = $("#slctDepartment").val();
        var ShiftId = $("#slctShift").val();
        if (DeptId != 0 && ShiftId != 0) {
            $.ajax({

                type: "POST",
                url: "/Booking/GetDoctorByDepartmentID",
                data: {
                    DeptId: DeptId,
                    ShiftId: ShiftId
                },

                success: function (res) {

                    $.each(res, function (i, e) {
                        $("#slctDoctor").append("<option value='" + e.id + "'>" + e.name + "</option>");
                    });
                }

            });
        }
    })
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!-- Validation Plugin Js -->

<script>
    if (@ViewBag.Success == 1) {
        //$("#exampleDataList").val("");
        //$("#slctDepartment").val("-1");
        //$("#slctShift").val("-1");
        //$("#time").val("mm/dd/yyy --:-- --");
             swal("Success", "You clicked the button!", "success").then(function () {
                 $(".A input").val("");
                 $("#exampleDataList").val("");
                 $("#slctDepartment").val("-1");
                 $("#slctShift").val("-1");
                 $("#time").val("mm/dd/yyy --:-- --");


                 

             }).then(function () {
                 window.location = "/Booking/Create";
             });

        }
</script>

UI/Views/Booking/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>