UI/Controllers/UsersController.cs
using BLL.Services.UsersServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IUsersServices users;
        public UsersController(UserManager<IdentityUser> userManager, IUsersServices users)
        {
            this.userManager = userManager;
            this.users = users;
        }


        #region Get Users
        public IActionResult GetUsers()
        {
            var AllUsers = users.GetAll();
          
            //var users = userManager.Users;
            return View(AllUsers);
        }
        #endregion



        #region Details
        public async Task<IActionResult> Details(string id)
        {
            var user = await users.GetByID(id);
            

            if (user != null)
            {
                return View(user);
            }

            return RedirectToAction("GetUsers");
        }
        #endregion



        #region Edit

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {

            var user = await users.GetByID(id);

            if (user != null)
            {
                return View(user);
            }

            return RedirectToAction("GetUsers");

        }

        [HttpPost]
        public async Task<IActionResult> Edit(IdentityUser model)
        {
            if (await users.Edit(model))
                return RedirectToAction("GetUsers");
            else
                return View();
            //var user = await userManager.FindByIdAsync(model.Id);

            //if (user != null)
            //{

            //    user.UserName = model.UserName;
            //    user.Email = model.UserName;


            //    var result = await userManager.UpdateAsync(user);

            //    if (result.Succeeded)
            //    {
            //        return RedirectToAction("GetUsers");
            //    }
            //    else
            //    {
            //        foreach (var item in result.Errors)
            //        {
            //            ModelState.AddModelError("", item.Description);
            //        }

            //        return RedirectToAction("GetUsers");
            //    }

            //}

            //return RedirectToAction("GetUsers");

        }
        #endregion


        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await users.GetByID(id);
            if (user != null)
            {
                return View(user);
            }
            return RedirectToAction("GetUsers");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(IdentityUser model)
        {
            if (await users.Delete(model.Id))
                return RedirectToAction("GetUsers");
            else
                return View();
        }
        #endregion
        [AcceptVerbs("GET", "POST")]
        public async Task <IActionResult> VerifyEmail(string email)
        {
            var user= await userManager.FindByEmailAsync(email);

            if (user!=null)
            {
                return Json($"Email {email} is already in use.");
            }

            return Json(true);
        }
        
    }
}

UI/Views/Users/Delete.cshtml
@model IdentityUser
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<form asp-controller="Users" asp-action="Delete" class="form-group">


    <input type="hidden" asp-for="Id" />


    <label asp-for="UserName">User Name</label>
    <input type="text" placeholder="User Name" asp-for="UserName" class="form-control" readonly />
    <br />

    <center>
        <input type="submit" value="Delete" class="btn btn-danger btn-block" />
    </center>

</form>

UI/Views/Users/Details.cshtml
@model IdentityUser
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<input type="text" asp-for="UserName" class="form-control" readonly />

<br />

<a asp-controller="Users" asp-action="GetUsers" class="btn btn-primary Submit">Go To Users</a>

UI/Views/Users/Edit.cshtml
@model IdentityUser
@{
    ViewBag.Title = "Edit";
}

<h2>Edit User</h2>

<form asp-controller="Users" asp-action="Edit" class="form-group">

    <label asp-for="UserName">User Name</label>
    <br />
    <input type="text" placeholder="User Name" asp-for="UserName" class="form-control" />
    <br />

    <center>
        <button type="submit" class="btn btn-info" ><i class="fa-solid fa-pen-to-square"></i> </button>
        <a asp-controller="Users" asp-action="GetUsers" class="btn btn-secondary "> <i class="fa-solid fa-rectangle-xmark"></i> </a>
    </center>

</form>

UI/Views/Users/GetUsers.cshtml
@model IEnumerable<IdentityUser>
@{
    ViewBag.Title = "All Users";
}

<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">All Users</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                All Users
            </li>
        </ol>
    </nav>
</div>
<div class="card-body patients-wating" id="patients-wating">
    <table id="example1" class="table table-striped Actions">
        <thead>
            <tr class="table-bg">
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>  <p>@item.UserName</p></td>
                    <td>
                        <a asp-action="Details" asp-controller="Users" asp-route-id="@item.Id" class="btn btn-primary " ><i style="font-size:large" class="fa fa-eye"></i></a>&nbsp;&nbsp;|&nbsp;&nbsp;
                        <a asp-action="Edit" asp-controller="Users" asp-route-id="@item.Id" class="btn btn-info " ><i style="font-size:large" class="fa fa-edit"></i></a>
                        @*<a asp-action="Delete" asp-controller="Users" asp-route-id="@item.Id"><i style="font-size:large" class="fa fa-trash"></i></a>*@
                    </td>


                </tr>
            }
        </tbody>
    </table>
</div>
<button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>