UI/Controllers/LabController.cs
using BLL.Services.LabServices;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LabController : Controller
    {
        private readonly ILabServices lab;

        public LabController(ILabServices lab)
        {
            this.lab = lab;
        }
        public IActionResult AddLab()
        {
            ViewBag.lab = "";
            return View();
        }
        [HttpPost]
        public IActionResult AddLab(LabViewModel Lab)
        {
            var data = lab.Add(Lab);
            if (data == true)
            {
                ViewBag.lab = "true";
                return View();

            }
            else
            {
                ViewBag.lab = "1";
                return View(Lab);

            }
        }
        public IActionResult UpdateLab(int id)
        {

            var data = lab.GetByID(id);
            ViewBag.lab = "";
            return View(data);
        }
        [HttpPost]
        public IActionResult UpdateLab(LabViewModel Lab)
        {

            var data = lab.Update(Lab);
            if (data == true)
            {
                return RedirectToAction("ViewAllLab");

            }
            else
            {
                ViewBag.lab = "1";
                return View(Lab);
            }

        }
        public IActionResult ViewAllLab()
        {
            var data = lab.GetAll();
            return View(data);

        }
        public IActionResult GetAllDeletedLab()
        {
            var data = lab.GetAllDeletd();
            return View(data);

        }
       
        public JsonResult Delete(int id)
        {

            var data = lab.Delete(id);
           
            return Json(data);

        }
        public JsonResult UpdateDelete(int id)
        {

            var data = lab.UpdateDelete(id);
           
            return Json(data);

        }
    }
}

UI/Views/Lab/AddLab.cshtml
@model LabViewModel
@{
    ViewData["Title"] = "Create Analysis";
}
<!-- page content -->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">Create Analysis</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                Create Analysis
            </li>
        </ol>
    </nav>
    @if (ViewBag.lab != "" && ViewBag.lab != "1")
    {
        <script>
            swal({
                title: "Success!",
                text: "Analysis Created Successfully",
                type: "success"
            }).then(function () {
                window.location = "/Lab/AddLab";
            });
        </script>
    }


    <form asp-controller="Lab" asp-action="AddLab" method="post" >
        <!-- Basic Information  -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card shadow">
                    <div class="header ms-3 pt-2">
                        <h3>Analysis Information</h3>
                    </div>
                    <div class="body">
                        @*Validation*@
                        @if (ViewBag.lab == "1")
                        {
                            <div class="row clearfix">
                                <div class="col-sm-12 mb-4">
                                    <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 " role="alert">
                                        Please Change Lab Name it Used befoer
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                                aria-label="Close"></button>
                                    </div>
                                    <div class="form-floating">
                                    </div>
                                </div>
                            </div>
                        }
                        <!-- Analysis Name -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="form-floating input-group">
                                    <span class="input-group-text">
                                        <i class="fa-solid fa-flask"></i>
                                    </span>
                                    <input asp-for="Name" type="text" class="form-control input" placeholder="Lab Name"
                                           required />
                                    <label for="floatingInput">Lab Name</label>
                                </div>
                                <span asp-validation-for="Name" class="text-danger"></span>

                            </div>
                        </div>
                        <!-- Analysis Price -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="form-floating input-group">
                                    <span class="input-group-text">
                                        <i class="fa-solid fa-tags"></i>
                                    </span>
                                    <input asp-for=Price type="text" class="form-control input" placeholder="Lab Price"
                                           required />
                                    <label for="floatingInput">Lab Price</label>
                                </div>
                                <span asp-validation-for="Price" class="text-danger"></span>

                            </div>
                        </div>
                        <div class="row clearfix">
                            <!-- Status -->
                            <div class="col-sm-6 mb-3">
                                <label class="col-form-label col-sm-3 col-md-2 label-align d-inline">
                                    Status
                                </label>
                                <div class="col-8 col-sm-8 col-md-8 floatingInput">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" value="false" class="flat " name="Delete" />
                                            active
                                        </label>
                                    </div>
                                    <div class="radio mt-1">
                                        <label>
                                            <input type="radio" value="true" class="flat" name="Delete" />
                                            not active
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- buttons -->
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="button-submit">
                    <div class="body social">
                        <div class="row clearfix">
                            <div class="form-group mb-4 pt-2">
                                <button type="submit" class="btn  Submit">Create</button>
                                <button type="reset" class="btn btn-outline-secondary">Reset</button>
                            </div>
                        </div>
                        <button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>

                    </div>
                </div>
            </div>
        </div>
    </form>

</div>

<!-- /page content -->
<!-- footer content -->
<!-- /footer content -->
<!-- move to up -->
<div class="up-btn shadow position-fixed rounded-lg" id="moveTop">
    <button type="button" class="btn btn-lg shadow text-light m-0">
        <i class="fa-solid fa-turn-up"></i>
    </button>
</div>

<!-- js -->
<script src="~/jquery/jquery.min.js"></script>
<script src="~/jquery-validate/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    let alert = document.querySelectorAll('.alert')
    input = document.querySelectorAll('.input');

    for (let i = 0; i < input.length; i++) {
        input[i].addEventListener('keyup', () => {
            if (input[i].value === "")
                alert[i].classList.remove('d-none')
            else
                alert[i].classList.add('d-none')
        })
    }
</script>

UI/Views/Lab/GetAllDeletedLab.cshtml
@model IEnumerable<DAL.Models.LabViewModel>
@{
    ViewData["Title"] = "All Deleted Analysis";
    int a = 0;
}

<!-- page content -->
@if (ViewBag.lab == "Delete")
{
    <script>
        swal("Deleted Success!", "You clicked the button!", "Denger");

    </script>
}
<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">All Deleted Analysis</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                All Deleted Analysis
            </li>
        </ol>
    </nav>
    <div>
    </div>
    <div class="card-body patients-wating" id="patients-wating">
        <table id="example1" class="table table-striped Actions">
            <thead>
                <tr class="table-bg">
                    <th scope="col" class="numbers">#</th>
                    <th scope="col">Analysis Name</th>
                    <th scope="col">Analysis Price</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    a = a + 1;
                    <tr>

                        <th scope="row" class="numbers">
                            <p> @a </p>
                        </th>
                        <td>
                            <p class="">@item.Name</p>
                        </td>

                        <th scope="col" class="w">
                            <p>@item.Price</p>
                        </th>

                        <td class="w">
                            <div class="row">

                                <a onclick="Delete(@item.Id)" class="col-6 btn delete m-0 p-1 p-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete">
                                    <i class="fa-solid fa-trash-can"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>
<button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>

<!-- /page content -->
<!-- footer content -->
<!-- /footer content -->
<!-- move to up -->
<div class="up-btn shadow position-fixed rounded-lg" id="moveTop">
    <button type="button" class="btn btn-lg shadow text-light m-0">
        <i class="fa-solid fa-turn-up"></i>
    </button>
</div>

<!-- js -->
<script>
    let alert = document.querySelectorAll('.alert')
    input = document.querySelectorAll('.input');

    for (let i = 0; i < input.length; i++) {
        input[i].addEventListener('keyup', () => {
            if (input[i].value === "")
                alert[i].classList.remove('d-none')
            else
                alert[i].classList.add('d-none')
        })
    }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script type="text/javascript">

    function Delete(id) {
        swal({
            title: `Are you sure you want to delete this record?`,
            text: "If you delete this, it will be gone forever.",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({

                        type: "POST",
                        url: "/Lab/UpdateDelete",
                        data: {
                            id: id,

                        },

                        success: function (res) {

                            swal("Deleted!", "Your imaginary file has been archived.", "success");
                            window.location = "/Lab/GetAllDeletedLab"

                        }

                    });
                }
            });
    }


</script>

UI/Views/Lab/UpdateLab.cshtml
@model DAL.Models.LabViewModel
@{
    ViewData["Title"] = "Edit Analysis";
}
<!-- page content -->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">Edit Analysis</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                Edit Analysis
            </li>
        </ol>
    </nav>



    <form asp-controller="Lab" asp-action="UpdateLab" method="post" style="height: 100vh;">
        <!-- Basic Information  -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card shadow">
                    <div class="header ms-3 pt-2">
                        <h3>Analysis Information</h3>
                    </div>
                    <div class="body">
                        @*Validation*@
                        @if (ViewBag.lab == "1")
                        {
                            <div class="row clearfix">
                                <div class="col-sm-12 mb-4">
                                    <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 " role="alert">
                                        Please Change Lab Name  it Used befoer
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>
                                    <div class="form-floating">
                                    </div>
                                </div>
                            </div>
                        }
                        <!-- Analysis Name -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 d-none" role="alert">
                                    You should check in on some of those fields below.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                                <div class="form-floating">
                                    <input asp-for=Name type="text" class="form-control input" placeholder="Lab Name" required />
                                    <label for="floatingInput">Lab Name</label>
                                </div>
                            </div>
                        </div>
                        <!-- Analysis Price -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 d-none" role="alert">
                                    You should check in on some of those fields below.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                                <div class="form-floating">
                                    <input asp-for=Price type="text" class="form-control input" placeholder="Lab Price" required />
                                    <label for="floatingInput">Lab Price</label>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <!-- Status -->
                            <div class="col-sm-6 mb-3">
                                <label class="col-form-label col-sm-3 col-md-2 label-align d-inline">
                                    Status
                                </label>
                                <div class="col-8 col-sm-8 col-md-8 floatingInput">
                                    @if (Model.Delete == false)
                                    {
                                        <div class="radio">

                                            <label>
                                                <input type="radio" value="false" class="flat "
                                                       name="Delete" checked />
                                                active
                                            </label>
                                        </div>
                                        <div class="radio mt-1">
                                            <label>
                                                <input type="radio" value="true" class="flat" name="Delete" />
                                                not active
                                            </label>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="radio">

                                            <label>
                                                <input type="radio" value="false" class="flat "
                                                       name="Delete" />
                                                active
                                            </label>
                                        </div>
                                        <div class="radio mt-1">
                                            <label>
                                                <input checked type="radio" value="true" class="flat" name="Delete" />
                                                not active
                                            </label>
                                        </div>
                                    }

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- buttons -->
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="button-submit">
                    <div class="body social">
                        <div class="row clearfix">
                            <div class="form-group mb-4 pt-2">
                                <button type="submit" class="btn  Submit">Edit</button>
                                <button type="reset" class="btn btn-outline-secondary">Reset</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- /page content -->
<!-- footer content -->
<!-- /footer content -->

<button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>

<!-- move to up -->
<div class="up-btn shadow position-fixed rounded-lg" id="moveTop">
    <button type="button" class="btn btn-lg shadow text-light m-0">
        <i class="fa-solid fa-turn-up"></i>
    </button>
</div>

<!-- js -->
<script>
    let alert = document.querySelectorAll('.alert')
    input = document.querySelectorAll('.input');

    for (let i = 0; i < input.length; i++) {
        input[i].addEventListener('keyup', () => {
            if (input[i].value === "")
                alert[i].classList.remove('d-none')
            else
                alert[i].classList.add('d-none')
        })
    }
</script>

UI/Views/Lab/ViewAllLab.cshtml
@model IEnumerable<DAL.Models.LabViewModel>
@{
    ViewBag.Title = "All Analysis";
    int a = 0;
}

<!-- page content -->
@if (ViewBag.lab == "Delete")
{
    <script>
        swal("Deleted Success!", "You clicked the button!", "Denger");

    </script>
}
<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">All Analysis</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                All Analysis
            </li>
        </ol>
    </nav>
    <div>
</div>
        <div class="card-body patients-wating" id="patients-wating">
            <table id="example1" class="table table-striped Actions">
                <thead>
                    <tr class="table-bg">
                        <th scope="col" class="numbers">#</th>
                        <th scope="col">Analysis Name</th>
                        <th scope="col">Analysis Price</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        a = a + 1;
                        <tr>

                            <th scope="row" class="numbers">
                                <p> @a </p>
                            </th>
                            <td>
                                <p class="">@item.Name</p>
                            </td>

                            <th scope="col" class="w">
                                <p>@item.Price</p>
                            </th>

                            <td class="w">
                                <div class="row w-75 m-aito">
                                    <a asp-controller="Lab" asp-action="UpdateLab" asp-route-id=@item.Id class="col-6 btn edite m-0 p-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Edite">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <a onclick="Delete(@item.Id)" class="col-6 btn delete m-0 p-1 p-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete">
                                        <i class="fa-solid fa-trash-can"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
<button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>

<!-- /page content -->
<!-- footer content -->
<!-- /footer content -->
<!-- move to up -->
<div class="up-btn shadow position-fixed rounded-lg" id="moveTop">
    <button type="button" class="btn btn-lg shadow text-light m-0">
        <i class="fa-solid fa-turn-up"></i>
    </button>
</div>

<!-- js -->
<script>
    let alert = document.querySelectorAll('.alert')
    input = document.querySelectorAll('.input');

    for (let i = 0; i < input.length; i++) {
        input[i].addEventListener('keyup', () => {
            if (input[i].value === "")
                alert[i].classList.remove('d-none')
            else
                alert[i].classList.add('d-none')
        })
    }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script type="text/javascript">

    function Delete(id) {
        swal({
            title: `Are you sure you want to delete this record?`,
            text: "If you delete this, it will be gone forever.",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({

                        type: "POST",
                        url: "/Lab/Delete",
                        data: {
                            id: id,

                        },

                        success: function (res) {

                            swal("Deleted!", "Your imaginary file has been archived.", "success");
                            window.location = "/Lab/ViewAllLab"

                        }

                    });
                }
            });
    }


</script>