UI/Controllers/SurgeryController.cs
using BLL.Services.SurgeryServices;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SurgeryController : Controller
    {
        private readonly ISurgeryServices surgery;

        public SurgeryController(ISurgeryServices surgery)
        {
            this.surgery = surgery;
        }
        public IActionResult Index()
        {
            return View();
        }




        public IActionResult AddSurgery()
        {
            ViewBag.Surgery = "";
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddSurgery(SurgeryViewModel model)
        {
            var result = await surgery.Create(model);
            if (result != 0)
            {
                ViewBag.Surgery = "true";
                return View();
            }
            else
            {
                ViewBag.Surgery = "1";
                return View(model);
            }
        }




        public IActionResult UpdateSurgery(int id)
        {
          var data=surgery.GetByID(id);
            return View(data);
        }
        [HttpPost]
        public IActionResult UpdateSurgery(SurgeryViewModel surgeryvm)
        {
            var data=surgery.Edit(surgeryvm);

            return RedirectToAction("ViewAllSurgery");
        }


        public IActionResult ViewAllSurgery()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var data=surgery.Delete(id);
            return Json(data);
        }
    }
}

UI/Views/Surgery/AddSurgery.cshtml
@model SurgeryViewModel
@{
    ViewBag.Title = "Create Surgery";
}
<!-- page content -->
<script src="~/jquery/jquery.min.js"></script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">Create Surgery</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                Create Surgery
            </li>
        </ol>
    </nav>
    @if (ViewBag.Surgery != "" && ViewBag.Surgery != "1")
    {
<script>
    swal({
        title: "Success!",
        text: "Surgery Created Successfully",
        type: "success"
    }).then(function () {
        window.location = "/Surgery/AddSurgery";
    });
</script>
    }


    <form class="A1" asp-controller="Surgery" asp-action="AddSurgery" method="post">
        <!-- Basic Information  -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card shadow">
                    <div class="header ms-3 pt-2">
                        <h3>Surgery Information</h3>
                    </div>
                    <div class="body">
                        @*Validation*@
                        @if (ViewBag.Surgery == "1")
                        {
                            <div class="row clearfix">
                                <div class="col-sm-12 mb-4">
                                    <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 " role="alert">
                                        Please Change Surgery Name it Used before
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                    </div>
                                    <div class="form-floating">
                                    </div>
                                </div>
                            </div>
                        }
                        <!-- Surgery Name -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="form-floating input-group">
                                    <span class="input-group-text">
                                        <i class="fa-solid fa-file-waveform"></i>
                                    </span>
                                    <input asp-for="Name" type="text" class="form-control input"
                                           placeholder="Surgery Name" required />
                                    <label for="floatingInput">Surgery Name</label>
                                </div>
                                <span asp-validation-for="Name" class="text-danger"></span>

                            </div>
                        </div>
                        <!-- Surgery Price -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="form-floating input-group">
                                    <span class="input-group-text">
                                        <i class="fa-solid fa-tags"></i>
                                    </span>
                                    <input asp-for=Price type="text" class="form-control input"
                                           placeholder="Surgery Price" required />
                                    <label for="floatingInput">Surgery Price</label>
                                </div>
                                <span asp-validation-for="Price" class="text-danger"></span>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- buttons -->
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="button-submit">
                    <div class="body social">
                        <div class="row clearfix">
                            <div class="form-group mb-4 pt-2">
                                <button onclick="history.back()" class="btn btn-secondary">
                                    <i class="fas fa-angle-double-left"></i> Back
                                </button>
                                <button type="submit" class="btn Submit">Create</button>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- /page content -->
<!-- footer content -->
<!-- /footer content -->
<!-- move to up -->
<div class="up-btn shadow position-fixed rounded-lg" id="moveTop">
    <button type="button" class="btn btn-lg shadow text-light m-0">
        <i class="fa-solid fa-turn-up"></i>
    </button>
</div>

<!-- js -->
<script src="~/jquery/jquery.min.js"></script>
<script src="~/jquery-validate/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    let alert = document.querySelectorAll('.alert')
    input = document.querySelectorAll('.input');

    for (let i = 0; i < input.length; i++) {
        input[i].addEventListener('keyup', () => {
            if (input[i].value === "")
                alert[i].classList.remove('d-none')
            else
                alert[i].classList.add('d-none')
        })
    }
</script>

UI/Views/Surgery/UpdateSurgery.cshtml
@model SurgeryViewModel
@{
    ViewBag.Title = "Update Surgery ";
}
<!-- page content -->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">Create Surgery</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                Create Surgery
            </li>
        </ol>
    </nav>
  

    <form asp-controller="Surgery" asp-action="UpdateSurgery" method="post" style="height: 100vh;">
        <!-- Basic Information  -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card shadow">
                    <div class="header ms-3 pt-2">
                        <h3>Surgery Information</h3>
                    </div>
                    <div class="body">
                       <input type="hidden"asp-for="Id" />
                        <!-- Surgery Name -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 d-none" role="alert">
                                    You should check in on some of those fields below.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                                <div class="form-floating">
                                    <input asp-for="Name" type="text" class="form-control input" placeholder="Surgery Name" required />
                                    <label for="floatingInput">Surgery Name</label>
                                    <span asp-validation-for="Name" class="text-danger"></span>

                                </div>
                            </div>
                        </div>
                        <!-- Surgery Price -->
                        <div class="row clearfix">
                            <div class="col-sm-12 mb-4">
                                <div class="alert alert-warning alert-dismissible fade show m-auto mb-1 d-none" role="alert">
                                    You should check in on some of those fields below.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                                <div class="form-floating">
                                    <input asp-for=Price type="text" class="form-control input" placeholder="Surgery Price" required />
                                    <label for="floatingInput">Surgery Price</label>
                                    <span asp-validation-for="Price" class="text-danger"></span>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- buttons -->
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="button-submit">
                    <div class="body social">
                        <div class="row clearfix">
                            <div class="form-group mb-4 pt-2">
                                <button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>
                                <button type="submit" class="btn  Submit">Edit</button>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- /page content -->
<!-- footer content -->
<!-- /footer content -->
<!-- move to up -->
<div class="up-btn shadow position-fixed rounded-lg" id="moveTop">
    <button type="button" class="btn btn-lg shadow text-light m-0">
        <i class="fa-solid fa-turn-up"></i>
    </button>
</div>

<!-- js -->
<script src="~/jquery/jquery.min.js"></script>
<script src="~/jquery-validate/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    let alert = document.querySelectorAll('.alert')
    input = document.querySelectorAll('.input');

    for (let i = 0; i < input.length; i++) {
        input[i].addEventListener('keyup', () => {
            if (input[i].value === "")
                alert[i].classList.remove('d-none')
            else
                alert[i].classList.add('d-none')
        })
    }
</script>

UI/Views/Surgery/ViewAllSurgery.cshtml
@{
    ViewBag.Title = "All Surgery";
    int a = 0;
}
@inject BLL.Services.PatientSurgeryServices.IPatientSurgeryServices Surgery

<!-- page content -->

<div class="x_content mt-0">
    <h2 class="p-2 rounded ps-3">All Analysis</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                Home
            </li>
            <li class="breadcrumb-item" aria-current="page">
                All Surgery
            </li>
        </ol>
    </nav>
    <div>
</div>
        <div class="card-body patients-wating" id="patients-wating">
            <table id="example1" class="table table-striped Actions">
                <thead>
                    <tr class="table-bg">
                        <th scope="col" class="numbers">#</th>
                        <th scope="col">Surgery Name</th>
                        
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Surgery.GetAll())
                    {
                        a = a + 1;
                        <tr>

                            <th scope="row" class="numbers">
                                <p> @a </p>
                            </th>
                            <td>
                                <p class="">@item.Name</p>
                            </td>

                            

                            <td class="w">
                                <div class="row w-75 m-aito">
                                    <a asp-controller="Surgery" asp-action="UpdateSurgery" asp-route-id=@item.Id class="col-6 btn edite m-0 p-1" target="_blank" data-bs-toggle="tooltip" data-bs-placement="top" title="Edite">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <a onclick="Delete(@item.Id)" class="col-6 btn delete m-0 p-1 p-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete">
                                        <i class="fa-solid fa-trash-can"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
<button onclick="history.back()" class="btn btn-secondary"><i class="fas fa-angle-double-left"></i> Back </button>

<!-- /page content -->
<!-- footer content -->
<!-- /footer content -->
<!-- move to up -->
<div class="up-btn shadow position-fixed rounded-lg" id="moveTop">
    <button type="button" class="btn btn-lg shadow text-light m-0">
        <i class="fa-solid fa-turn-up"></i>
    </button>
</div>

<!-- js -->
<script>
    let alert = document.querySelectorAll('.alert')
    input = document.querySelectorAll('.input');

    for (let i = 0; i < input.length; i++) {
        input[i].addEventListener('keyup', () => {
            if (input[i].value === "")
                alert[i].classList.remove('d-none')
            else
                alert[i].classList.add('d-none')
        })
    }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
<script type="text/javascript">

    function Delete(id) {
        swal({
            title: `Are you sure you want to delete this record?`,
            text: "If you delete this, it will be gone forever.",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({

                        type: "POST",
                        url: "/Surgery/Delete",
                        data: {
                            id: id,

                        },

                        success: function (res) {

                            swal("Deleted!", "Your imaginary file has been archived.", "success");
                            location.reload();

                        }

                    });
                }
            });
    }


</script>